version: "3.9"
services:
  items-services:
    build: items-service
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI = "mongodb://mongodb:27017/"
      - DATABASE_NAME=items_db
      - COLLECTION_NAME=items

  challenges-serivce:
    build: challenges-service
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI = "mongodb://mongodb:27017/"
      - DATABASE_NAME=challenges_db
      - COLLECTION_NAME=challenges

  users-service:
    build: users-service
    ports:
      - "8002:8002"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI = "mongodb://mongodb:27017/"
      - DATABASE_NAME=users_db
      - COLLECTION_NAME=users

  categories-service:
    build: categories-service
    ports:
      - "8003:8003"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI = "mongodb://mongodb:27017/"
      - DATABASE_NAME=categories_db
      - COLLECTION_NAME=categories
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"   