version: "3.9"
services:
  items-services:
    build: items-service
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI = "mongodb://mongodb:27017/"
      - DATABASE_NAME=items_db
      - COLLECTION_NAME=items

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"